"""empty message

Revision ID: 2d81577ca29c
Revises: 
Create Date: 2019-01-27 19:34:13.956624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d81577ca29c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bname', sa.String(length=256), nullable=False),
    sa.Column('btype', sa.String(length=256), nullable=False),
    sa.Column('loa', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bname'),
    sa.UniqueConstraint('btype'),
    sa.UniqueConstraint('loa')
    )
    op.drop_table('boats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boats',
    sa.Column('bname', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('btype', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('loa', sa.REAL(), autoincrement=False, nullable=True)
    )
    op.drop_table('marina')
    # ### end Alembic commands ###
